# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("music/new.gif"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 60, 801, 121))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(85)
        font.setBold(False)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#F4E4BC")
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(410, 230, 451, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color:#F4E4BC;\n"
"background-color:#D9822B")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(410, 360, 451, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(20)
        font.setBold(True)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color:#F4E4BC;\n"
"background-color:#D9822B")
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushgame = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushgame.setGeometry(QtCore.QRect(450, 500, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(36)
        font.setBold(False)
        self.pushgame.setFont(font)
        self.pushgame.setStyleSheet("color:#F4E4BC;\n"
"background-color:#6A2E2E;\n"
"border:#3AF1F")
        self.pushgame.setObjectName("pushgame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "MENU"))
        self.radioButton.setText(_translate("MainWindow", "Player vs Bot"))
        self.radioButton_2.setText(_translate("MainWindow", "2  Player Game"))
        self.pushgame.setText(_translate("MainWindow", "START"))
