# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("music/player1_won.gif"))
        self.label.setObjectName("label")
        self.rematch_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rematch_2.setGeometry(QtCore.QRect(270, 510, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        self.rematch_2.setFont(font)
        self.rematch_2.setStyleSheet("background-color:#AB47BC;\n"
"color:#FFFFFF;\n"
"border:#D4A017;")
        self.rematch_2.setObjectName("rematch_2")
        self.menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(820, 510, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(36)
        font.setBold(True)
        self.menu.setFont(font)
        self.menu.setStyleSheet("background-color:#EC407A;\n"
"color:#FFFFFF;\n"
"border:#FFD700;")
        self.menu.setObjectName("menu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rematch_2.setText(_translate("MainWindow", "Rematch"))
        self.menu.setText(_translate("MainWindow", "MENU"))
