# Form implementation generated from reading ui file 'wel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("music/pla.gif"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 30, 701, 121))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(72)
        font.setBold(True)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color:#F4E4BC;\n"
"text-shadow:0 0 8px rgba(255,180,80,0.6),\n"
" 2px 2px 6px rgba(0,0,0,0.7);\n"
"letter-spacing:3px")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 530, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(26)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:F4E4BC;\n"
"background-color:#A15A1F\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 130, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#FFFFFF")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Climb And Slide"))
        self.pushButton.setText(_translate("MainWindow", "PLAY"))
        self.label_3.setText(_translate("MainWindow", "Roll. Slide. Climb. Win"))
